package ShippingHub;

import java.awt.Toolkit;

/**
* Class:        AboutShippingHub
* File:		AboutShippingHub.java
* Description:	A form to display information about the Shipping Hub application.
* @author:	Ryu Muthui
* Environment:	PC, Windows 7, jdk:1.7.0_10, NetBeans IDE 7.2
* Date:		04/24/2013
* @version:	1.01
* @see:         java.awt.Toolkit;
* History Log:	Created on April 9, 2013, Completed April 24th 2013.
*/
public class AboutShippingHub extends javax.swing.JFrame 
{

    /**
     * Creates new form AboutShippingHub
     */
    public AboutShippingHub() 
    {
        initComponents();
        
        //Sets the form to display at the center.
        setLocationRelativeTo(null);
        
        //Sets icon image on form.
        this.setIconImage(Toolkit.getDefaultToolkit()
                .getImage("src\\ShippingHub\\Images\\Parcel.png"));
        
        //Sets close button as default and request focus to it as it loads.
        this.getRootPane().setDefaultButton(closeJButton); 
        closeJButton.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeJButton = new javax.swing.JButton();
        aboutImageJLabel = new javax.swing.JLabel();
        aboutJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Shipping Hub");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        closeJButton.setMnemonic('c');
        closeJButton.setText("Close");
        closeJButton.setToolTipText("Click to close the About form.");
        closeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJButtonActionPerformed(evt);
            }
        });

        aboutImageJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ShippingHub/Images/AboutShippingHub.png"))); // NOI18N

        aboutJLabel.setText("<HTML> \nAbout Shipping Hub: <BR><BR>\nThis program is an application to track the Parcels that pass through\na shipping hub. When the user clicks the application’s Scan New Button, the application\ngenerates an ID and arrival time for the new Parcel. Once a Parcel has been scanned,\nthe user can enter recipient’s name and shipping address for the Parcel. The other menu\noptions allow for the user to remove or modify the information of Parcels that have\nalready been scanned. The user can navigate through the list of scanned Parcels by using\nthe Back or Next Buttons. Finally, users are able to view a numeric list of all Parcels\ndestined for a particular state. Additional features include that previously scanned\n parcels can be recalled and be kept track of even after the user has exited and restarted\nthe application at a later time. Removing Parcels defaults to the last scanned parcel.<BR><BR>\nAuthor: Ryu Muthui <BR><BR>\nVersion:1.01; Created 04/24/2013<BR>\nPlatform: PC, Windows 7, jdk:1.7.0_10, NetBeans IDE 7.3 <BR>\nCopyright: Ryu Muthui Productions (2013)<BR>\n</HTML>\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aboutImageJLabel))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(aboutJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutImageJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(closeJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(301, 301, 301)
                    .addComponent(aboutJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(21, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the About form when selected.
     * @param evt closeJButtonActionPerformed
     */
    private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AboutShippingHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AboutShippingHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AboutShippingHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AboutShippingHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AboutShippingHub().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutImageJLabel;
    private javax.swing.JLabel aboutJLabel;
    private javax.swing.JButton closeJButton;
    // End of variables declaration//GEN-END:variables
}
