package GolfDataBase;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*  Class:	<b>AddMemberGUI</b>
*  File:	AddMemberGUI.java
* <pre>
*  Description:	A form to add new memebers to the database.
*  @author:	<i>Ryu Muthui and Siqi Zhang</i>
*  Environment:	PC, Windows 7, jdk1.7_17, NetBeans 7.3
*  Date:	5/15/2013
*  Hours:       7 hours
*  @version	1.01
*  @see         java.awt.Toolkit
*  @see         javax.swing.JOptionPane
* </pre>
*  History Log:	Started 4/30/2013, Completed 5/15/2013.
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class AddMemberGUI extends javax.swing.JDialog 
{
    //instance Variables
    boolean isComplete = false;
    MemberInformation newAddedMember;
    
    /**
     * Creates new form AddMemberGUI
     */
    public AddMemberGUI(java.awt.Frame parent, boolean modal) 
    {
        super(parent, modal);
        
        initComponents();
        
        //Sets the form to display in the center on start up.
        setLocationRelativeTo(null);
        
        //Sets icon image on form.
        this.setIconImage(Toolkit.getDefaultToolkit()
                .getImage("src/Resources/CityImage.png"));
        
        //Set addNewMemberJButton as the default button.
        this.getRootPane().setDefaultButton(addNewMemberJButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        titleImageJLabel = new javax.swing.JLabel();
        informationJPanel = new javax.swing.JPanel();
        firstNameJLabel = new javax.swing.JLabel();
        lastNameJLabel = new javax.swing.JLabel();
        emailJLabel = new javax.swing.JLabel();
        phoneNumberJLabel = new javax.swing.JLabel();
        rankJLabel = new javax.swing.JLabel();
        firstNameJTextField = new javax.swing.JTextField();
        lastNameJTextField = new javax.swing.JTextField();
        emailJTextField = new javax.swing.JTextField();
        phoneNumberJFormattedTextField = new javax.swing.JFormattedTextField();
        rankJFormattedTextField = new javax.swing.JFormattedTextField();
        golfImageJLabel = new javax.swing.JLabel();
        addNewMemberJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add/Edit Player Data");

        titleJLabel.setBackground(new java.awt.Color(153, 255, 255));
        titleJLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("<html>\nGolf Database Input:<BR>\nEnter member information in the fiields to add them into <BR>\nthe database or modify the fields to update current member\ninformation.\n<html>");

        titleImageJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/GolfDB_Title_Logo.png"))); // NOI18N
        titleImageJLabel.setToolTipText("");

        informationJPanel.setBackground(new java.awt.Color(204, 255, 255));
        informationJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Player Information:"));

        firstNameJLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        firstNameJLabel.setText("First Name:");

        lastNameJLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lastNameJLabel.setText("Last Name:");

        emailJLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailJLabel.setText("Email Address:");

        phoneNumberJLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoneNumberJLabel.setText("Phone Number:");

        rankJLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rankJLabel.setText("Player Rank:");

        firstNameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        lastNameJTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        emailJTextField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        try {
            phoneNumberJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneNumberJFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneNumberJFormattedTextFieldFocusGained(evt);
            }
        });

        try {
            rankJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        golfImageJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/GolfDB_Hole_Image.png"))); // NOI18N

        javax.swing.GroupLayout informationJPanelLayout = new javax.swing.GroupLayout(informationJPanel);
        informationJPanel.setLayout(informationJPanelLayout);
        informationJPanelLayout.setHorizontalGroup(
            informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(informationJPanelLayout.createSequentialGroup()
                        .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lastNameJLabel)
                            .addComponent(emailJLabel)
                            .addComponent(firstNameJLabel))
                        .addGap(18, 18, 18)
                        .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameJTextField)
                            .addComponent(firstNameJTextField)
                            .addComponent(emailJTextField)))
                    .addGroup(informationJPanelLayout.createSequentialGroup()
                        .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rankJLabel)
                            .addComponent(phoneNumberJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneNumberJFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(rankJFormattedTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(golfImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        informationJPanelLayout.setVerticalGroup(
            informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationJPanelLayout.createSequentialGroup()
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(firstNameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informationJPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneNumberJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneNumberJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(informationJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rankJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rankJLabel)))
                    .addComponent(golfImageJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        addNewMemberJButton.setMnemonic('A');
        addNewMemberJButton.setText("Add New Member");
        addNewMemberJButton.setToolTipText("Select to add new member.");
        addNewMemberJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewMemberJButtonActionPerformed(evt);
            }
        });

        cancelJButton.setMnemonic('A');
        cancelJButton.setText("Cancel");
        cancelJButton.setToolTipText("Cancel entry of new member");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        clearJButton.setMnemonic('C');
        clearJButton.setText("Clear");
        clearJButton.setToolTipText("Clear the entry fields");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleImageJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addNewMemberJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(clearJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(informationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleImageJLabel)
                    .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cancelJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(addNewMemberJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Closes the AddNewMemberJDialogue frame when clicked.
     * @param evt cancelJButtonActionPerformed
     */
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        //Click to close the addNewMember JDialogue
        isComplete = false;
        GolfDataBaseGUI.setNewMember(newAddedMember, isComplete);
        this.dispose();
    }//GEN-LAST:event_cancelJButtonActionPerformed

    /**
     * Checks for validation in all entry fields. It then creates a temp array object
     * to hold the new data being entered. Then passes the data back to main GUI to be 
     * added under the addJButton.
     * @param evt addNewMemberJButtonActionPerformed
     */
    private void addNewMemberJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewMemberJButtonActionPerformed
        
        GolfDataBaseGUI myArray = new GolfDataBaseGUI();
        
        //used for determining if email and phone number is valid inputs.
        boolean isEmail = Validation.isEmail(emailJTextField.getText().trim());
        boolean isPhoneNumber = Validation.isNumber(phoneNumberJFormattedTextField.getText().trim());
        
        //input validation for each entry fields
        try
        {   
            //Validate the firstname and lastname field so that they are not empty
            if(firstNameJTextField.getText().trim().isEmpty() || lastNameJTextField.getText().trim().isEmpty() )
            {   
                JOptionPane.showMessageDialog(null, "Name Fields can not be left blank.", "Invalid Entry!",
                JOptionPane.WARNING_MESSAGE);
                firstNameJTextField.requestFocus();
            }
            else 
            {   
                //check for the validate email input
                if(isEmail == false)
                {
                    JOptionPane.showMessageDialog(null, "Email entry is invalid." + 
                    "Example: abc@abc.com", "Invalid Entry!", JOptionPane.WARNING_MESSAGE);
                    emailJTextField.requestFocus();
                }
                else
                {   
                    //check for the validate phonenumber input
                    if(isPhoneNumber == false)
                    {
                        JOptionPane.showMessageDialog(null, "Phone Number entry is invalid.", "Invalid Entry!",
                        JOptionPane.WARNING_MESSAGE);
                        phoneNumberJFormattedTextField.requestFocus();
                    }
                    else
                    {   
                        //assign the input to the variables
                        String firstName = firstNameJTextField.getText().trim();
                        String lastName = lastNameJTextField.getText().trim();
                        String eMail = emailJTextField.getText().trim();
                        String phoneNumber = phoneNumberJFormattedTextField.getText().trim();
                        int memberRank = Integer.parseInt(rankJFormattedTextField.getText()); 

                        //check to see if there is duplicate rank.
                        boolean existRank = false;
                        
                        for(int i = 0; i < myArray.memberDatabase.size(); i++)
                        {
                            if(memberRank == myArray.memberDatabase.get(i).getRank())
                            {
                                existRank = true;
                                break;
                            }
                        }
                        if(existRank)
                        {
                            JOptionPane.showMessageDialog(null, 
                                    "Another member already exists with that same rank",
                                    "Invalid Input!",
                            JOptionPane.WARNING_MESSAGE);
                            rankJFormattedTextField.selectAll();
                            rankJFormattedTextField.requestFocus(); 
                        }
                        else
                        {
                            if(memberRank == 0)
                            {
                                JOptionPane.showMessageDialog(null, 
                                    "Entry of Rank 0 is not allowed.",
                                    "Invalid Input!",
                            JOptionPane.WARNING_MESSAGE);
                            rankJFormattedTextField.selectAll();
                            rankJFormattedTextField.requestFocus();
                            }
                            else
                            {
                                memberRank = myArray.memberDatabase.size()+1;
                                newAddedMember = new MemberInformation
                                          (firstName,lastName,eMail,phoneNumber,memberRank);
                                isComplete = true;
                                GolfDataBaseGUI.setNewMember(newAddedMember, isComplete);
                                this.dispose();
                            }
                        }
                     }
                 }
             }
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(null, "Enter valid numbers from 1 to 9 for rank.", "Invalid Entry!!",
                JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addNewMemberJButtonActionPerformed
    
    /**
     * Clears all the entry fields when selected so that the user can start over with a blank slate.
     * @param evt clearJButtonActionPerformed
     */
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        // Clear the entry fields when selected.
        firstNameJTextField.setText(null);
        lastNameJTextField.setText(null);
        emailJTextField.setText(null);
        phoneNumberJFormattedTextField.setText(null);
        rankJFormattedTextField.setText(null); 
    }//GEN-LAST:event_clearJButtonActionPerformed
 
    /**
     * When focused is gained it check to see if valid entry has been made, if not
     * resets the field to blank, so that the user must enter numerical values and not 
     * strings.
     * @throws Exception
     * @param evt phoneNumberJFormattedTextFieldFocusGained
     */
    private void phoneNumberJFormattedTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneNumberJFormattedTextFieldFocusGained
        //Set the zipJFormattedTextField field to blank.
        try{Integer.parseInt(phoneNumberJFormattedTextField.getText());}
        catch(Exception ex){phoneNumberJFormattedTextField.setText("");}
    }//GEN-LAST:event_phoneNumberJFormattedTextFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMemberGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddMemberGUI dialog = new AddMemberGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewMemberJButton;
    private javax.swing.JButton cancelJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JLabel emailJLabel;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JLabel firstNameJLabel;
    private javax.swing.JTextField firstNameJTextField;
    private javax.swing.JLabel golfImageJLabel;
    private javax.swing.JPanel informationJPanel;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameJTextField;
    private javax.swing.JFormattedTextField phoneNumberJFormattedTextField;
    private javax.swing.JLabel phoneNumberJLabel;
    private javax.swing.JFormattedTextField rankJFormattedTextField;
    private javax.swing.JLabel rankJLabel;
    private javax.swing.JLabel titleImageJLabel;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables
}
